---
name: CodePolicy

# Controls when the action will run.
on:
  push:
    # branches: ["NEVER"]
  pull_request:
  workflow_dispatch:

jobs:
  CodePolicy:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.codepolicy.znuny.yml@dev
