---
name: Lint

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Lint:
    uses: dennykorsukewitz/DK4/.github/workflows/reusable.lint.yml@dev