---
name: Lint
on:
  push:
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Branch Name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: ${GITHUB_REF##*/}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}