---
name: GitHub Pages

on:
  push:
    branches: ["dev", "dev-update"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Pages:
    uses: dennykorsukewitz/DK4/.github/workflows/reusable.pages.yml@dev
