---
name: PDF

on:
  push:
    # branches: ["NEVER"]
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    # paths:
    #   - 'doc/de/*.md'
    #   - 'doc/en/*.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PDF:
    uses: dennykorsukewitz/DK4/.github/workflows/reusable.pdf.yml@dev