---
name: UnitTest

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  UnitTest:
    uses: dennykorsukewitz/DK4/.github/workflows/reusable.unittest.yml@dev
    secrets:
      GIST: ${{ secrets.GIST }}
