---
name: UnitTest

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ZNUNY_REF:
        description: "The branch, tag or SHA to checkout. (e.g.: rel-6_5)"
        required: false
        type: string
        default: rel-6_5
      FRAMEWORK:
        description: "The framework to use. (e.g.: otrs, znuny)"
        required: false
        type: string
        default: otrs

jobs:
  UnitTest:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.unittest.znuny.yml@dev
    secrets:
      GIST: ${{ secrets.GIST }}
    with:
      ZNUNY_REF: ${{ inputs.ZNUNY_REF || 'rel-6_5' }}
      FRAMEWORK: ${{ inputs.FRAMEWORK || 'otrs' }}
