---
name: UnitTest

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  UnitTest-MySQL:
    name: UnitTest:MySQL
    runs-on: ubuntu-22.04 # ubuntu-latest
    container: debian:10-slim
    env:
      DB: mysql
      MYSQL_USER: "otrs"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "otrs"
    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: "otrs"
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_PASSWORD: "secret"
          MYSQL_DATABASE: "otrs"
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          path: package

      - name: Check out module-tools
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          repository: OTRS/module-tools
          path: module-tools

      - name: Check out Znuny
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          repository: znuny/Znuny
          path: znuny

      - name: Install dependencies
        run: znuny/.github/workflows/ci/dependencies.sh

      - name: Setup Znuny
        run: |
          cd znuny

          a2dismod mpm_event mpm_worker
          a2enmod perl deflate filter headers mpm_prefork
          useradd -d /opt/otrs -c 'OTRS user' -g www-data -s /bin/bash -M otrs

          # link and create files
          ln -sf "$PWD" /opt/otrs
          ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/apache2/sites-enabled/zzz_otrs.conf
          cp /opt/otrs/Kernel/Config.pm.dist /opt/otrs/Kernel/Config.pm
          mkdir -p /opt/otrs/var/tmp

          # start apache
          apachectl start

          # MySQL
          .github/workflows/ci/config-mysql.sh

          # run needed scripts
          /opt/otrs/bin/otrs.SetPermissions.pl
          su -c "bin/otrs.CheckSum.pl -a create" - otrs
          touch /opt/otrs/installed

          # prepare Selenium tests
          .github/workflows/ci/config-selenium.sh

          su -c "bin/otrs.Console.pl Maint::Config::Rebuild" - otrs
          su -c "bin/otrs.Console.pl Admin::Config::Update --setting-name CheckEmailAddresses --value 0" - otrs

      - name: Link Package
        run: |
          cd "$GITHUB_WORKSPACE"
          apt-get install -y libdatetime-perl libgetopt-complete-perl libio-interactive-perl libstring-similarity-perl libxmlrpc-lite-perl
          su -c "$GITHUB_WORKSPACE/module-tools/bin/otrs.ModuleTools.pl Module::File::Link package znuny" - otrs
          cd znuny
          su -c "bin/otrs.Console.pl Maint::Cache::Delete" - otrs
          su -c "bin/otrs.Console.pl Maint::Config::Rebuild --cleanup" - otrs

      - name: Run UnitTests
        run: |
          su -c "bin/otrs.CheckSum.pl -a create" - otrs
          su -c "bin/otrs.Console.pl Dev::UnitTest::Run --sopm-file DK4Znuny-QuickDelete.sopm" - otrs
